dings"!==b&&oIb(b)&&
("paragraph"!==b&&"list"!==b||!nZc(a,d))&&(d=Svi(e,d,rIb(b)))){d=d.UB();break a}d=null}if(!(b in h.C))throw Mb("Call to getStyleProvider for disabled style type: "+Xa(b)).C;return new Rvi(b,h.C[b].C,k,c,d)}function Zvi(a){for(var b in a)return!1;return!0}function $vi(a){S.call(this,a);this.H=new It;this.Ia(this.H);this.H.ao(!1);Jt(this.H,!1);Kt(this.H,!0);this.H.setPosition(1,0)}v($vi,S);p=$vi.prototype;
p.Ja=function(){S.prototype.Ja.call(this);this.getHandler().listen(this.getElement(),"pointerdown",this.Rfb)};p.Ca=function(){S.prototype.Ca.call(this);var a=this.getElement(),b=this.qa();this.Pa=b.Ca("DIV","docs-calloutbubble-anchor");b.appendChild(a,this.Pa);ks(this.Pa,"docs-calloutbubble-anchor");this.H.Ob("docs-calloutbubble-bubble");this.H.wi(this.Pa);this.H.render(a)};p.fia=function(){return this.H.zb()};
p.setVisible=function(a){if(a!=this.isVisible()&&this.dispatchEvent(a?"show":"hide")){var b=this.getElement();b&&(R(b,a),this.H.setVisible(a),this.H.fd())}};p.isVisible=function(){return this.H.isVisible()};function awi(a,b,c){Vq(a.Pa,b,c);a.H.fd()}p.Rfb=function(a){ch.hf&&Sf(73)&&a.target.setPointerCapture(a.pointerId)};function bwi(a,b){var c=null,d=a.Zh();b=dK(a.lh(),b);a=new PI(b?b:a.lh(),!1,!0);Pl(a,function(e){return null!=e&&kk(e)&&"A"==e.tagName?(c=e.href,!0):e==d});return c}
function cwi(a,b,c){return T('<div class="'+U("docs-link-linksuggestion-text")+'"><div class="'+U("docs-link-linksuggestion-title")+'"'+(b?' title="'+U(b)+'"':"")+">"+Jr(a)+"</div>"+(c?'<div class="'+U("docs-link-linksuggestion-url")+'">'+Jr(c)+"</div>":"")+"</div>")}
function dwi(a){var b=a.xba,c=a.mj;a=a.ids;b='<div class="'+U("docs-link-chipselectedlinksuggestion")+'">'+uw("docs-icon-img "+c)+cwi(Or(""+Jr(b)))+'<div id="'+U(a.Gqa)+'" class="'+U("docs-link-chipselectedlinksuggestion-hide")+'" tabIndex="0" aria-role="button" aria-label="';b+=Qr("Discard the currently selected suggestion");b+='" role="button">'+uw("docs-icon-img docs-icon-close-small")+"</div></div>";return T(b)}
function ewi(a){a=a.title;return T('<div class="docs-link-infilelinksuggestiongroup-cb">'+uw("docs-icon-img docs-zippy-open","docs-link-infilelinksuggestiongroup-cb-openarrow")+uw("docs-icon-img docs-zippy-closed","docs-link-infilelinksuggestiongroup-cb-closearrow")+'<div class="docs-link-infilelinksuggestiongroup-cb-title">'+Jr(a)+"</div></div>")}
function fwi(a){var b=a.qc,c=a.Cbb;a=a.ESa;b='<div class="'+U("docs-link-insertlinkbubble")+'" dir="'+(b?"rtl":"ltr")+'" tabIndex="0" role="dialog" aria-label="';b+=Qr("Edit or Insert link");b+='"><div class="'+U("docs-link-insertlinkbubble-toppane")+'">'+Jr(c)+'</div><div class="'+U("docs-link-insertlinkbubble-bottompane")+'">'+Jr(a)+"</div></div>";return T(b)}
function gwi(a){var b=T,c='<div class="'+U("docs-link-insertlinkbubble-urlcomponent")+'">';var d='<label class="'+U("docs-link-insertlinkbubble-url-label")+'" for="'+U(a.sfa)+'">';d=T(d+"Link</label>");return b(c+d+'<div class="'+U("docs-link-insertlinkbubble-urlholder")+'" id="'+U(a.kFb)+'"><div id="'+U(a.sfa)+'" spellcheck="false" autocomplete="off"></div><div class="'+U("docs-link-insertlinkbubble-linkchip")+'" id="'+U(a.ODb)+'"></div><div class="'+U("docs-link-insertlinkbubble-suggestionholder")+
'" id="'+U(a.j5)+'" tabIndex="-1"></div><div class="'+U("docs-link-insertlinkbubble-error")+'" id="'+U(a.keb)+'" role="alert"></div></div></div><div class="'+U("docs-link-insertlinkbubble-buttonbar")+'" id="'+U(a.Gca)+'"></div>')}function hwi(a){var b=a.ids;return T(fwi(Kr({Cbb:Or(""),ESa:Or(""+gwi(b))},a)))}
function iwi(a){var b=a.ids;a=a.yMb;var c='<div class="'+U("docs-link-linksuggestioncontentbox")+'"><div class="'+U("docs-link-linksuggestioncontentbox-offlinenotice")+'" id="'+U(b.oQa)+'">';c=c+'Some suggestions are not available offline.</div><div class="'+(U("docs-link-linksuggestioncontentbox-suggestion-holder")+'" id="'+U(b.j5)+'" role="listbox"></div><div class="'+U("docs-link-linksuggestioncontentbox-statusbar")+'" id="'+U(b.LQa)+'"><div class="'+U("docs-link-linksuggestioncontentbox-statusmessage")+
'" id="'+U(b.MQa)+'"></div><div class="'+U("docs-link-linksuggestioncontentbox-statusindicator")+'" id="'+U(b.cQa)+'"></div></div>'+(a?'<div class="'+U("docs-link-linksuggestioncontentbox-explore")+'" id="'+U(b.BJa)+'" tabIndex="0">'+uw("docs-icon-img docs-icon-search-this-document")+'<div class="'+U("docs-link-linksuggestioncontentbox-exploretext")+'" id="'+U(b.CJa)+'"></div></div>':"")+"</div>");return T(c)}
function jwi(a){var b=a.xba,c=a.yba,d=a.mj,e=a.textClass,f=a.ids,h=a.url;a=a.qLb;e='<div class="'+U("docs-link-linksuggestion")+" "+U(e)+'" tabIndex="0" role="option">';d=T('<div class="'+U("docs-link-linksuggestion-icon")+'">'+uw("docs-icon-img "+d)+"</div>");b=e+d+(a?cwi(Or(""+Jr(b)),""+c,""+a):cwi(Or(""+Jr(b)),""+c));h&&(b+='<a class="'+U("docs-link-linksuggestion-testlink")+'" id="'+U(f.XQa)+'" href="'+U(Sr(h))+'" target="_blank" rel="noreferrer" tabIndex="0" aria-label="',b+=Qr("Open link in a new tab"),
b+='">'+uw("docs-icon-img docs-icon-popout")+"</a>");return T(b+"</div>")}
function kwi(a,b){a=a.ids;return T("<div class='docs-link-urlinput-url-container' id=\""+U(a.lFb)+'"><input type="text" class="'+U("docs-link-urlinput-url")+'" id="'+U(a.sfa)+'" role="combobox" aria-haspopup="true" aria-autocomplete="list" aria-owns="'+U(a.j5)+'" tabIndex="0"/><div class=\''+U("docs-link-urlinput-action-icon-container")+"' id=\""+U(a.jFb)+'">'+Uu({id:a.iFb,Kd:"docs-link-urlinput-action-icon",content:Or('<div class="'+U("docs-icon")+" "+U("goog-inline-block")+'"><div id="'+U(a.hFb)+
'" class="'+U("docs-icon-img-container")+" "+U("docs-icon-img")+'">&nbsp;</div></div>'),width:1},b)+"</div></div>")}function lwi(a,b,c){if(!b||!a)return null;a=ovc(Vsc(a));if(!a)return b="https://drive.google.com/open?id="+Xa(b),c?Xa(b)+"&resourcekey="+Xa(c):b;var d=obb();d.C=b;b=mbb(lbb(nbb(d,a),"https"),"");!c||vea(b.F,{resourcekey:c});return b.build("/edit")}var mwi=/(?:mailto:)?([\w.!#$%&'*+-/=?^_`{|}~]+@[A-Za-z0-9.-]+\.(?:com|org|net|edu|gov|aero|biz|cat|coop|info|int|jobs|mobi|museum|name|pro|travel|arpa|asia|xxx|[a-z][a-z])\b)/i;function nwi(){};function owi(a,b,c){this.C=a;this.D=b;this.F=Ob(c,nwi)?c:0}v(owi,Ta);function pwi(a,b){return new owi(a.C,b,a.F)}owi.prototype.isEmpty=function(){return Vb(kc(Xa(this.C)+Xa(this.D)))};function qwi(a){return Vb(kc(a.C))?a.D:a.C}owi.prototype.equals=function(a){return Wa(this,a)?!0:a instanceof owi?Wa(this.D,a.D)&&Wa(this.C,a.C):!1};owi.prototype.wh=function(){return Wb([this.D,this.C])};function z6(a,b,c,d,e,f,h){this.J=a;this.O=b;this.C=c;this.L=d;this.F=e;this.D=f;this.H=h}v(z6,Ta);z6.prototype.getType=g("L");z6.prototype.getUrl=g("O");z6.prototype.getMimeType=g("H");function rwi(a,b){this.C=b}v(rwi,Ta);rwi.prototype.getUrl=g("C");function A6(a,b,c,d,e){S.call(this,e);this.F=b;this.L=Jr(a);e=this.qa();this.O=e.fA(yk(e,Dr(this.L)));this.J=c;this.ma=d;this.R=ur(this,swi);this.C=null}v(A6,S);p=A6.prototype;p.getType=g("ma");p.getUrl=g("F");p.yAa=g("O");p.Ca=function(){S.prototype.Ca.call(this);var a={};a.xba=this.L;a.yba=this.O;a.mj=this.D();a.textClass=this.H();var b=this.J;if("drive"==b||"web"==b){var c=pF(this.F);c&&(a.url=wMb(c))}"web"==b&&(a.qLb=this.F);a.ids=this.R;this.mb(Gr(jwi,a,void 0,this.qa()))};
p.Ja=function(){S.prototype.Ja.call(this);if(this.C=this.qa().getElement(this.R.XQa))this.getHandler().Ue(this.C,Hm,this.Kic),fu(this.C,"Open link in a new tab",void 0);this.getHandler().Ue(this.getElement(),Hm,this.i9b)};p.Kic=function(a){a.stopPropagation()};p.i9b=function(a){if(a.altKey&&this.C)try{this.C.focus()}catch(c){}else{var b=new twi(this.F,this.O,this.yAa(),this.J,this.getType(),!1,this);this.dispatchEvent(b)}a.stopPropagation()};
function twi(a,b,c,d,e,f,h){Cm.call(this,"docs-link-suggestion-linkselect",h);this.url=a;this.C=d;this.Sp=e;this.anchorText=b;this.D=c}v(twi,Cm);var swi={XQa:"dlstl"};function uwi(a,b){A6.call(this,a.getLabel(),"","action","action",b);this.ea=a}v(uwi,A6);uwi.prototype.D=function(){return this.ea.getIcon()};uwi.prototype.H=m("docs-link-linksuggestion-action-text");function vwi(a,b,c){S.call(this,c);this.F=a;this.D=b;this.C=ur(this,wwi)}v(vwi,S);vwi.prototype.Ca=function(){var a={};a.ids=this.C;a.xba=this.F;a.mj=this.D;a=Gr(dwi,a);this.mb(a)};vwi.prototype.Ja=function(){S.prototype.Ja.call(this);var a=this.qa().getElement(this.C.Gqa);if(!a)throw Error("Hide element should have been found");this.getHandler().Ue(a,Hm,this.H)};vwi.prototype.H=function(a){var b=this.getElement();R(b,!1);this.dispatchEvent("hide");a.stopPropagation()};var wwi={Gqa:"dllsch"};function xwi(a){switch(a){case "document":return"Document";case "presentation":return"Slide";case "spreadsheet":return"Spreadsheet";case "drawing":return"Drawing";case "link":return"Web link";case "bookmark":return"Bookmark";case "heading":return"Heading";case "slide":return"Slide";case "namedRange":return"Named range"}return""};function ywi(a,b,c,d){A6.call(this,a,b,"infile",c,d)}v(ywi,A6);ywi.prototype.D=function(){var a=this.getType();switch(a){case "bookmark":return"docs-icon-bookmark";case "heading":return"docs-icon-paragraph";case "slide":return"docs-icon-presentation";case "spreadsheet":return"docs-icon-spreadsheet";case "namedRange":return"docs-icon-named-range";default:throw Error("Unsupported Infile suggestions type encountered: "+a);}};ywi.prototype.H=m("docs-link-linksuggestion-link-text");
ywi.prototype.yAa=function(){var a=A6.prototype.yAa.call(this),b=this.getType();"slide"!=b&&(b=xwi(b))&&(a=b+(": "+a));return a};function zwi(a){Cm.call(this,"uu",a)}v(zwi,Cm);function Awi(a){Cm.call(this,"docs-ilb-bf",a)}v(Awi,Cm);function Bwi(a,b,c){Cm.call(this,"docs-ilb-af",c);this.Tp=a;this.C=b}v(Bwi,Cm);function Cwi(a,b){Cm.call(this,"docs-ilb-il",b);this.url=a}v(Cwi,Cm);function Dwi(a,b){B.call(this);this.ea=a;this.Ha=b;this.Pa=new Pm(this);this.oa(this.Pa);this.ma=this.xa=!1;this.H=0;this.Ea=!1;this.C=this.J=this.R=this.F=null;this.O=[];this.D=null;this.Ma=[];this.Aa=[];this.Qa=!1;this.L=!0;this.Pa.listen(this.ea,"docs-ilb-bf",this.nHb).listen(this.ea,"docs-ilb-af",this.kGb).listen(this.ea,"docs-ilb-il",this.v8b).listen(this.ea,"docs-link-suggestion-linkselect",this.Mvb)}v(Dwi,B);p=Dwi.prototype;
p.reset=function(){this.ma=this.xa=!1;this.H=0;this.F=null;this.Ea=!1;this.J=this.R=null;this.Ma=[];this.Aa=[];this.L=!0;this.D=this.C=null;this.O=[]};function Ewi(a,b){a.L=b}function Fwi(a,b){var c=b.find(function(d){return!!d.D});c&&a.O.push(c.D);if(a.L){if(!(a.xa&&0<a.H))for(b=ha(b),c=b.next();!c.done;c=b.next())c=c.value,a.Ma.push(c),Jvi(a.D,VL(c.getUrl()))}else for(b=ha(b),c=b.next();!c.done;c=b.next())c=c.value,a.Aa.push(c),Kvi(a.D,VL(c.getUrl()))}
function Gwi(a,b){var c=b.filter(function(e){return"infile"===e.C}),d=c.filter(function(e){return"bookmark"===e.getType()});c=c.filter(function(e){return"heading"===e.getType()});Avi(M(a.C,sMd,7),d.length);zvi(a.C.getHeader(),c.length);Fwi(a,b)}function Hwi(a){a.L||(a.Aa=[],nU(a.D,7))}p.nHb=function(){this.xa&&(this.H++,this.J||(this.J=Date.now()))};
p.kGb=function(a){var b=a.Tp,c=b.filter(function(e){return"drive"===e.C}),d=b.filter(function(e){return"web"===e.C});a=a.C?qwi(a.C).length:0;0<d.length&&(Bvi(M(this.C,uMd,8),d.length),Gvi(M(this.D,uNd,12),d.length));Fvi(M(this.C,yMd,10),a);Ivi(M(this.D,sNd,11),a);0<c.length&&Dvi(M(this.C,wMd,9),c.length);this.xa=!0;Fwi(this,b)};p.v8b=function(a){a=a.url;Iwi(this,a);this.F=a};
p.Mvb=function(a){K(this.D,2,!0);switch(a.C){case "web":var b=M(this.C,uMd,8);K(b,3,!0);b=M(this.D,uNd,12);K(b,3,!0);break;case "drive":b=M(this.C,wMd,9);K(b,3,!0);break;case "infile":"bookmark"===a.Sp?(b=M(this.C,sMd,7),K(b,2,!0)):"heading"===a.Sp&&(b=this.C.getHeader(),K(b,2,!0))}Iwi(this,a.url)};function Jwi(a,b){return Kwi(a).filter(function(c){return c.C===b})}function Kwi(a){return a.L?a.Ma:a.Aa}
function Iwi(a,b){var c=Jwi(a,"drive"),d=Jwi(a,"web");Cvi(M(a.C,uMd,8),d.findIndex(function(h){return h.getUrl()===b}));Hvi(M(a.D,uNd,12),d.findIndex(function(h){return h.getUrl()===b}));d=c.findIndex(function(h){return h.getUrl()===b});if(-1===d){var e=ntc(b);null!==e&&(d=c.findIndex(function(h){return ntc(h.getUrl())===e}))}Evi(M(a.C,wMd,9),d);c=Kwi(a).findIndex(function(h){return h.getUrl()===b});if(-1===c){var f=ntc(b);null!==f&&(c=Kwi(a).findIndex(function(h){return ntc(h.getUrl())===f}))}else"infile"===
Kwi(a)[c].C&&(c=-1);K(a.D,3,c)};function Lwi(a,b){S.call(this,b);this.J=a;this.D=-1}v(Lwi,S);p=Lwi.prototype;p.Ca=function(){S.prototype.Ca.call(this);ks(this.getElement(),"docs-link-linksuggestiongroup")};p.Ja=function(){S.prototype.Ja.call(this);this.getHandler().listen(this.getElement(),"keydown",this.Nvb)};p.Nvb=function(a){if(ir(this.zb())){switch(a.keyCode){case 38:var b=-1;break;case 40:b=1;break;default:return}this.$Da(this.D+b)&&(a.preventDefault(),a.stopPropagation())}};
p.$Da=function(a){if(0>a||a==this.jc())return!1;try{this.Bc(a).getElement().focus(),this.D=a}catch(b){return!1}return!0};p.Ysa=function(){if(0<this.jc())try{this.Bc(0).getElement().focus(),this.D=0}catch(a){}};p.Eea=function(){if(0<this.jc())try{var a=this.jc();this.Bc(a-1).getElement().focus();this.D=a-1}catch(b){}};function Mwi(a,b){b=new Lwi(b,void 0);for(var c=0;c<a.length;++c)b.Ia(a[c],!0);return b};function Nwi(a,b,c,d,e){d=void 0===d?null:d;A6.call(this,a,b,"drive",c,e);this.ea=d}v(Nwi,A6);Nwi.prototype.D=function(){if(this.ea)return Ctc(this.ea);switch(this.getType()){case "document":return"docs-icon-document";case "presentation":return"docs-icon-punch";case "spreadsheet":return"docs-icon-spreadsheet";case "drawing":return"docs-icon-drawing";default:return"docs-icon-file-blue"}};Nwi.prototype.H=m("docs-link-linksuggestion-link-text");function Owi(a,b){Lwi.call(this,"infile",b);this.L=a;this.C=this.bh=this.H=this.F=null}v(Owi,Lwi);p=Owi.prototype;p.Ca=function(){Lwi.prototype.Ca.call(this);var a=this.qa(),b=this.getElement();this.C=Gr(ewi,{title:this.L});this.F=a.Ca("DIV");this.H=new HJ(this.C,this.F);a.appendChild(b,this.C);a.appendChild(b,this.F)};p.zb=function(){if(!this.F)throw Error("No suggestion holder found in infile link suggestion group");return this.F};
p.Ja=function(){Lwi.prototype.Ja.call(this);this.bh||(this.bh=new Cs(this.C),this.oa(this.bh));this.getHandler().listen(this.H,"toggle",this.nic).listen(this.C,"keypress",this.R8b).listen(this.bh,"focusout",this.d1b)};p.d1b=function(){ms(this.C,"docs-link-infilelinksuggestiongroup-cb-keyboardfocus")};p.R8b=function(a){13==a.keyCode&&(a.stopPropagation(),a.preventDefault())};p.nic=function(a){os(this.C,"docs-link-infilelinksuggestiongroup-cb-open",a.JI)};p.Ysa=function(){Pwi(this)};
p.Eea=function(){this.H.ZF()?Lwi.prototype.Eea.call(this):Pwi(this)};p.$Da=function(a){var b=document.activeElement==this.C;return-1!=a||b?Lwi.prototype.$Da.call(this,a):Pwi(this)};function Pwi(a){try{return a.C.focus(),ks(a.C,"docs-link-infilelinksuggestiongroup-cb-keyboardfocus"),a.D=-1,!0}catch(b){}return!1}p.getTitle=g("L");function Qwi(a,b,c,d){A6.call(this,a,b,"web",c,d)}v(Qwi,A6);Qwi.prototype.D=m("docs-icon-web-result");Qwi.prototype.H=m("docs-link-linksuggestion-link-text");function Rwi(a){a=sd(a,Swi);a=Due(a,function(c){return c.J});var b=[];he(a,function(c,d){switch(d){case "infile":Id(b,Twi(c));break;case "action":b.push(Mwi(c,d));break;case "drive":var e=Math.min(c.length,hd(A(),"docs-esckmdsl"));b.push(Mwi(c.slice(0,e),d));break;case "web":e=Math.min(c.length,hd(A(),"docs-esckmwsl"));b.push(Mwi(c.slice(0,e),d));break;default:throw Error("Unknown corpus type: "+d);}});return b}
function Swi(a){var b=a.getUrl(),c=T(a.J),d=a.C,e=a.getType();switch(d){case "web":return new Qwi(c,b,e);case "drive":return new Nwi(c,b,e,a.getMimeType());case "infile":return new ywi(c,b,e);case "action":return new uwi(a.F);default:throw Error("Unknown corpus: "+d);}}function Twi(a){var b=[];a=Due(a,function(c){return c.getType()});he(a,function(c,d){var e=b.push;d=Uwi(d);d=new Owi(d,void 0);for(var f=0;f<c.length;++f)d.Ia(c[f],!0);e.call(b,d)});return b}
function Uwi(a){switch(a){case "bookmark":return"Bookmarks";case "heading":return"Headings";case "slide":return"Slides in this presentation";case "spreadsheet":return"Sheets in this spreadsheet";case "namedRange":return"Named ranges in this spreadsheet";default:throw Error("Unknown infile suggestion type: "+a);}}function Vwi(a,b){return Wwi[a.J]-Wwi[b.J]}var Wwi={infile:0,web:1,drive:2};function Xwi(){};function Ywi(a){if(!a)return!1;try{return!!Wl(1,a)&&!!Xl(a)}catch(b){return!1}}function Zwi(a){var b;if(b=!!a)b=a.match(mwi),b=(null!=b?b[0]:"")==a;return b};function $wi(a,b){S.call(this,b);var c=this;this.R=a;this.H=ur(this,axi);this.C=[];this.ea=this.L=this.xa=this.Ha=null;this.J=new AK(b,"docs-loading-indicator-small");this.Ia(this.J);this.Ea=new Du(this);this.Ea.Ab(O("docs-explore-sidebar"),wp,this.h5b);this.oa(this.Ea);this.Aa=new Nm;this.oa(this.Aa);this.Aa.wb(this.R.C,function(){c.L&&R(c.L,!Ov(c.R,1))});this.O=this.ma=this.D=null;this.F=-1}v($wi,S);p=$wi.prototype;p.Ca=function(){var a={};a.ids=this.H;a.yMb=y(A(),"docs-explore");a=Gr(iwi,a);this.mb(a)};
p.Ja=function(){S.prototype.Ja.call(this);var a=this.qa();this.xa=a.getElement(this.H.LQa);this.Ha=a.getElement(this.H.MQa);this.L=a.getElement(this.H.oQa);this.ea=a.getElement(this.H.j5);var b=a.getElement(this.H.cQa);b&&!this.J.getElement()&&this.J.render(b);bxi(this,"i");if(this.D=a.getElement(this.H.BJa))this.ma=a.getElement(this.H.CJa),this.getHandler().Ue(this.D,Hm,this.i5b);this.getHandler().listen(this.getElement(),"keydown",this.Ovb);this.L&&R(this.L,!Ov(this.R,1));cxi(this)};p.h5b=function(){cxi(this)};
function cxi(a){if(a.D){var b=Ywi(a.O);b=y(A(),"docs-explore")&&O("docs-explore-sidebar").isEnabled()&&!!a.O&&!b&&!Zwi(a.O);R(a.D,b)}}p.Ovb=function(a){var b=!1;switch(a.keyCode){case 40:b=dxi(this,1);break;case 38:b=dxi(this,-1)}b&&(a.preventDefault(),a.stopPropagation())};function exi(a){if(a.D&&ir(a.D))try{return a.D.focus(),!0}catch(b){}return!1}
function dxi(a,b){var c=document.activeElement==a.D;var d=a.F+b;if(d>a.C.length||0>d)return a.F=-1,!1;if(d==a.C.length){if(c||!exi(a))return a.F=-1,!1;a.F=a.C.length;return!0}1==b?a.C[d].Ysa():a.C[d].Eea();a.F=d;return!0}p.i5b=function(a){var b=tq(new sq,9).build(),c=new Xwi;O("docs-explore-menu").kb(c,b);a.stopPropagation()};
function bxi(a,b){if(a.getElement()){var c=a.qa(),d=a.Ha,e=a.xa;a.zb();switch(b){case "f":c.Ee(d,"Unable to retrieve suggestions at this time.");R(e,!0);R(d,!0);a.J.setVisible(!1);break;case "i":R(d,!1);R(e,!1);a.J.setVisible(!1);break;case "s":c.Ee(d,"Searching\u2026"),R(e,!0),R(d,!0),a.J.setVisible(!0)}}}p.zb=function(){if(this.ea)return this.ea;throw Error("Suggestion holder not found");};function fxi(a){for(var b=0;b<a.C.length;++b)a.removeChild(a.C[b],!0),Xf(a.C[b]);a.C=[];a.F=-1}
function gxi(a,b){a.O=b;if(a.ma){var c=a.qa();cxi(a);b&&(c.Ee(a.ma,"Find more"),a.D&&a.D.setAttribute("role","button"))}}var axi={cQa:"dllscli",oQa:"dllscon",BJa:"dllsce",CJa:"dllscet",LQa:"dllscsb",MQa:"dllscsm",j5:"dllscsh"};function hxi(a,b){S.call(this,b);this.O=a;this.C=new Qv("Paste a link, or search",b);this.Ia(this.C);this.J=this.D=this.L=this.H=null;this.F=new Vu("");this.oa(this.F)}v(hxi,S);p=hxi.prototype;p.Ca=function(){S.prototype.Ca.call(this);var a=ur(this,ixi);this.mb(Gr(kwi,{ids:a}))};
p.Ja=function(){S.prototype.Ja.call(this);this.C.Wa(vr(this,"dlbui"));this.H=vr(this,"dlbuic");this.L=vr(this,"dlbuai");this.J=vr(this,"dlbuaibc");R(this.J,!1);this.F.Wa(vr(this,"dlbuaib"));this.getHandler().listen(this.C.getElement(),"focus",this.m6b).listen(this.C.getElement(),"blur",this.k_b).listen(this.F,"action",this.tYb)};p.m6b=function(){ks(this.H,"docs-link-urlinput-url-container-focus")};p.k_b=function(a){ms(this.H,"docs-link-urlinput-url-container-focus");a.stopPropagation()};
p.getValue=function(){return this.C.getValue()};p.setValue=function(a){this.C.setValue(a);this.getElement().value=a};function jxi(a){a.D&&(ms(a.L,a.D.getIcon()),R(a.J,!1),a.F.iQ=!1,a.F.Zd(""));var b=a.O,c=a.C.getValue(),d=!!qH(c,b.C,!1,!0);b=(b=c.lastIndexOf(":")==c.length-1?qH(c.substring(0,c.length-1),b.C,!1,!0):null)&&XC(b.rect);a.D=d||b?skb:null;a.D&&(ks(a.L,a.D.getIcon()),R(a.J,!0),a.F.iQ=!0,a.F.Zd(a.D.getLabel()))}p.tYb=function(a){if(this.D){var b=new hM(ae(this.C.getValue()));this.D.kb(b)}a.stopPropagation()};
p.Ml=function(a){R(this.H,a)};p.clear=function(){this.C.clear()};p.reset=function(){this.C.reset()};p.isVisible=function(){return ir(this.H)};p.Wi=function(){return document.activeElement==this.C.getElement()};p.Ed=function(){return this.C.La()};var ixi={hFb:"dlbuai",iFb:"dlbuaib",jFb:"dlbuaibc",sfa:"dlbui",lFb:"dlbuic"};function kxi(a,b,c){this.F=a;this.C=b;this.D=c}kxi.prototype.getUrl=g("F");function lxi(a,b,c){this.C=a;this.F=b;this.D=c||null}lxi.prototype.getErrorCode=g("C");lxi.prototype.isValid=function(){return"none"==this.C};function mxi(a){a.isValid();return a.F};function B6(a,b,c,d,e,f,h,k){$vi.call(this,k);this.Kb=b;this.vd=a;this.C=new hxi(c,k);this.Ia(this.C);this.J=new $wi(e,k);this.Ia(this.J);this.Qa=BS("Apply",k);this.Ia(this.Qa);this.Aa=new On(this.Tba,200,this);this.oa(this.Aa);this.bd=!!h;this.Va=d;this.qb=this.F=null;this.Ea=!1;this.xa=this.L=this.R=null;this.Ra=!1;this.Ha=null;this.Cb=!1;this.Ma=this.ma=null;this.xc=!1;this.Dd=y(A(),"docs-egmd");this.O=new Dwi(this,f);this.oa(this.O)}v(B6,$vi);p=B6.prototype;
p.Ca=function(){$vi.prototype.Ca.call(this);var a={ids:{}};ve(a.ids,ur(this,nxi),this.JWa());a.qc=this.bd;a=Gr(this.tOa(),a);this.H.setContent(a);a=this.Da("docs-calloutbubble-bubble");ks(a,"docs-linkbubble-bubble");(this.Dd?ls:ns)(a,["docs-material","docs-material-bubble"])};p.tOa=function(){return hwi};p.JWa=function(){return{}};
p.initialize=function(){this.qa();this.C.render(vr(this,"dlbui"));var a=this.C.Ed();this.R=vr(this,"dlbsh");if(!this.R)throw Error("Suggestion holder element should be present");this.J.render(this.R);var b=vr(this,"dlbbb");if(!b)throw Error("Button bar element should be present");this.Qa.render(b);this.Wc=new nw(a);this.oa(this.Wc);this.bh=new Cs(this.fia());this.oa(this.bh);this.Lc=new Cs(a);this.oa(this.Lc);this.L=vr(this,"dlbuh");if(!this.L)throw Error("URL Holder element should have been present.");
this.Kc=new Cs(this.L);this.oa(this.Kc);a=this.fia().firstChild;this.xb=new Cw(a,this.qa());this.oa(this.xb);Dw(this.xb);this.Ce=new ot(this.getElement());this.oa(this.Ce);this.Ma=vr(this,"dlbem")};
p.Ja=function(){var a=this;$vi.prototype.Ja.call(this);this.Cb||(this.initialize(),this.Cb=!0);this.getHandler().listen(this.Wc,"input",this.bkc).listen(this.C.getElement(),"keydown",this.Q8b).listen(this.C.getElement(),"paste",function(){a.O.Ea=!0}).listen(this.J,"docs-link-suggestion-linkselect",this.Tvb).listen(this.J.getElement(),"keydown",this.P8b).listen(this.bh,"focusout",this.Qvb).listen(this.Kc,"focusout",this.o6b).listen(this.Lc,"focusin",this.k6b).listen(this.Qa,"action",this.Pvb).listen(this.getElement(),
oxi,this.Uvb).listen(this.R,"mousedown",this.S$b).listen(this.Ce,"key",this.Rvb).listen(this.getElement(),"keyup",this.Svb);pxi(this,!1)};p.dpc=function(){var a=document.activeElement;this.qa().contains(this.L,a)||C6(this,!1)};p.S$b=function(){mn(w(this.fxc,this,document.activeElement),0)};p.fxc=function(a){if(document.activeElement==this.R)try{a.focus()}catch(b){}};p.o6b=function(){mn(this.dpc,0,this)};p.k6b=function(){this.Tba();qxi(this,!1)};
function qxi(a,b){ok(a.L,b);b=!b;ok(a.C.C.getElement(),b)}p.Q8b=function(a){if(a.target)switch(a.keyCode){case 38:var b=this.J;exi(b)?b.F=b.C.length:0<b.C.length&&(b.C[b.C.length-1].Eea(),b.F=b.C.length-1);a.stopPropagation();a.preventDefault();break;case 40:b=this.J,0<b.C.length?(b.C[0].Ysa(),b.F=0):exi(b)&&(b.F=b.C.length),a.stopPropagation(),a.preventDefault()}};p.P8b=function(a){if(!a.defaultPrevented)switch(a.keyCode){case 40:case 38:rxi(this),a.stopPropagation()}};
function C6(a,b,c){c&&(fxi(a.J),a.Ha=null);a.R&&(b&&(b=a.J,b=ir(b.L)||ir(b.xa)||0<b.C.length||!!b.D&&ir(b.D)),R(a.R,b&&a.qa().contains(a.L,document.activeElement)))}p.Ilc=function(){if(!this.isDisposed()){var a=this.fia();a&&this.qa().contains(a,document.activeElement)||this.setVisible(!1)}};p.Qvb=function(){mn(this.Ilc,0,this)};p.Uvb=function(a){a.stopPropagation()};p.Svb=function(a){27==a.keyCode&&(ir(this.R)?(rxi(this),C6(this,!1),a.stopPropagation()):this.setVisible(!1))};
p.Rvb=function(a){13==a.keyCode&&(""!=this.C.getValue()&&(pxi(this,!(this.F&&this.F.isValid())),this.xc?ir(this.R)&&C6(this,!1):(this.dispatchEvent(new Cwi(mxi(this.F).getUrl(),this)),this.nCa())),a.stopPropagation())};p.Pvb=function(){pxi(this,!(this.F&&this.F.isValid()));ir(this.Ma)||(this.dispatchEvent(new Cwi(mxi(this.F).getUrl(),this)),this.nCa())};function sxi(a){a.dispatchEvent(new zwi(a))}
p.CGa=function(a){this.C.setValue(a.url);this.F=this.Va.C(a.url);txi(this);jxi(this.C);uxi(this,a.D)||rxi(this);this.xa=a.C;sxi(this);C6(this,!1);pxi(this,!1)};p.Tvb=function(a){qxi(this,!0);if("action"==a.C){a=a.target;var b=new hM(ae(this.C.getValue()));a.ea.kb(b)}else this.CGa(a)};p.bkc=function(){this.F=this.Va.C(this.C.getValue());sxi(this);pxi(this,!1);txi(this);this.xa=null;this.Tba();jxi(this.C)};p.Cva=function(){return ae(this.C.getValue())};
function pxi(a,b){if(a.xc=b){var c=a.ob,d=c.Ee,e=a.Ma,f=a.F;f.isValid();d.call(c,e,f.D?f.D:"utl"==f.C?"Links must be less than 2083 characters long":"Link doesn't look right. Typo?")}a.Ma&&R(a.Ma,b);os(a.C.H,"docs-link-urlinput-url-error",b)}function txi(a){a.Qa.Oa(""!=a.C.getValue())}
function uxi(a,b){var c=vr(a,"dlblc");if(!c)return!1;var d=a.C.getValue();if("#"!=d.charAt(0))return!1;for(var e=!1,f=Rwi(vxi(a)),h,k=0;k<f.length&&!h;++k)a:{h=f[k];for(var l=h.jc(),n=0;n<l;++n){var q=h.Bc(n);if(q.getUrl()==d){h=q;break a}}h=null}h&&h instanceof ywi&&(b&&(b="Link selected: "+b,a.L?gs(a.L,b):gs(c,b)),wxi(a,!1),b=h,b=new vwi(b.L,b.D(),b.qa()),a.ma=b,a.Ia(a.ma),a.ma.render(c),a.C.Wi()||a.lWa(),a.getHandler().Nc(a.ma,"hide",a.J0b),e=!0);Yf(f);return e}
function wxi(a,b){a.C.Ml(b);(a=a.$a("docs-link-insertlinkbubble-url-label"))&&R(a,b)}p.J0b=function(){xxi(this);rxi(this)};function xxi(a){a.ma&&(a.removeChild(a.ma,!0),a.ma.dispose(),wxi(a,!0),a.C.clear(),a.F=a.Va.C(""),txi(a),a.ma=null,a.L&&es(a.L,"label"))}p.Fea=function(){var a=new Yi,b=new $i;switch(this.xa){case "web":K(b,4,0);break;case "drive":K(b,4,1);break;case "infile":K(b,4,2)}if(this.F){var c=mxi(this.F).getUrl();c=VL(c);K(b,13,c)}K(b,2,this.Ra);Pi(a,18,b);return a};
p.nCa=function(){var a=mxi(this.F).getUrl();this.setVisible(!1);a=new hM(a);var b=uq(tq(new sq,1),this.Fea()).build();O("docs-insert-link").kb(a,b)};p.R7=function(){return new owi(this.C.getValue(),"")};p.nza=function(a){a=void 0===a?0:a;return new owi(this.C.getValue(),"",a)};
p.Tba=function(){var a=this;if(this.ma||this.F&&this.F.isValid()&&mxi(this.F).D)C6(this,!1),this.Aa.stop();else{var b=this.R7();gxi(this.J,this.Cva());if(b.equals(this.Ha))bxi(this.J,"i"),C6(this,!0),this.Aa.stop();else if(C6(this,!0,!0),b.equals(this.qb)){bxi(this.J,"s");Ewi(this.O,0===this.C.getValue().length);Hwi(this.O);b=vxi(this);yxi(this,b,!0);C6(this,!0);this.Ha=null;this.dispatchEvent(new Awi(this));b=zxi(this);for(var c={},d=ha(b.keys()),e=d.next();!e.done;c={O2:c.O2},e=d.next())e=e.value,
c.O2=this.nza(e),this.dispatchEvent(new Awi(this)),Axi(b.get(e),c.O2).Xd(function(f){return function(h){var k=f.O2;k.equals(a.R7())&&Bxi(a,k,h)}}(c),function(f){return function(){var h=f.O2,k=[];h.equals(a.R7())&&Bxi(a,h,k)}}(c));this.Aa.stop()}else this.qb=b,this.Aa.start()}};function zxi(a){var b=new Map;b.set(1,a.Kb);b.set(2,a.Kb);return b}function Bxi(a,b,c){a.dispatchEvent(new Bwi(c,b,a));a.Ha=b;yxi(a,c,!1);bxi(a.J,"i");C6(a,!0)}
function yxi(a,b,c){b=Rwi(b);Cxi(a);a=a.J;var d=[];if(c)fxi(a);else{d=a.C;for(c=0;c<a.C.length;++c)a.removeChild(a.C[c],!0);a.C=[]}c=d=Gd(d,b);Nd(c,Vwi);d=c;for(c=0;c<d.length;++c)a.Ia(d[c],!0),a.C.push(d[c]);a.F=-1;a.zb().scrollTop=0}p.KCa=function(){return this.C.Wi()};function Cxi(a){if(!a.KCa())try{qxi(a,!0),a.L.focus()}catch(b){}}p.lWa=function(){try{this.L&&this.L.focus()}catch(a){}};
function Dxi(a,b){null!=b&&0<b.length&&(a.xa=null,a.F=a.Va.C(b),b=a.F.isValid()?mxi(a.F).C:b,a.Ra=!!b,a.O.ma=a.Ra,a.C.setValue(b),txi(a),uxi(a),sxi(a),pxi(a,!1),a.Ea=!0,jxi(a.C));a.Ea&&(a.Tba(),a.Ea=!1)}p.reset=function(){this.C.reset();this.O.reset();this.F=null;txi(this);this.Ra=!1;this.xa=null;sxi(this);xxi(this);C6(this,!1,!0);this.Ha=null;gxi(this.J,null);jxi(this.C)};
p.setVisible=function(a,b){$vi.prototype.setVisible.call(this,a);b&&this.reset();if(a){a=this.O;a.R=Date.now();b=new AMd;var c=new qMd;b=Pi(b,6,c);c=new sMd;b=Pi(b,7,c);c=new uMd;b=Pi(b,8,c);c=new wMd;b=Pi(b,9,c);c=new yMd;b=Pi(b,10,c);a.C=b;b=new ANd;c=new uNd;b=Pi(b,12,c);c=new sNd;b=Pi(b,11,c);a.D=b;pxi(this,!1);this.Tba()}else if(this.qb=null,a=this.O,null!==a.R){c=a.R;a.R=null;var d=M(a.C,yMd,10);b=K(d,1,a.H);K(b,2,0<a.H);K(a.D,5,0<a.H);b=M(a.D,sNd,11);K(b,1,a.H);var e=Date.now();null!==a.J&&
(K(d,4,e-a.J),K(b,3,e-a.J));if(a.F){var f=VL(a.F);K(a.C,3,f);f=VL(a.F);K(a.D,1,f)}f=new Yi;var h=K(a.C,1,!a.ma);h=K(h,2,e-c);h=K(h,4,a.Ea);h=K(h,5,!!a.F);d=Pi(h,10,d);d=Pi(f,126,d);f=K(a.D,8,!a.ma);c=K(f,9,e-c);c=K(c,4,a.Ea);c=K(c,10,!!a.F);c=K(c,13,a.Qa);Mvi(d,Pi(c,11,b));0<a.O.length&&(b=new LNd,b=K(b,12,a.O[0]),b=K(b,13,a.O||[]),Pi(d,121,b));b=uq(tq(new sq,1),d).build();a.Ha.C(30105,b);(b=M(d,ANd,130))&&vi(b,10)&&vi(b,2)&&!vi(b,4)&&0<=J(b,3)&&(vi(b,5)?a.Ha.C(30366):a.Ha.C(30365))}};
function rxi(a){try{a.C.isVisible()?Tv(a.C.C):Cxi(a)}catch(b){}}function vxi(a){var b=Exi(a.vd);Gwi(a.O,b);return b}var nxi={Gca:"dlbbb",keb:"dlbem",ODb:"dlblc",j5:"dlbsh",kFb:"dlbuh",sfa:"dlbui"},oxi="mousedown pointerdown touchstart click contextmenu paste selectstart".split(" ");function Fxi(a){var b=a.ids,c=T,d='<label id="'+U(b.YQa)+'" class="'+U("docs-link-insertlinkbubble-text-label")+'" for='+Rr(b.gua)+">";d=""+T(d+"Text</label>");var e=T('<input type="text" class="'+U("docs-link-insertlinkbubble-text")+" "+U("jfk-textinput")+'" id="'+U(b.gua)+'"/>');return c(fwi(Kr({Cbb:Or(d+e),ESa:Or(""+gwi(b))},a)))};var Gxi=["footnote","horizontal_rule"],Hxi=["inline"];function Ixi(a){var b=a.C.getSelection().C();if(!b)return!0;a=a.Sa();var c=b.Qg(),d=b.Nk();b=a.C.slice(c,d);a=[Yvi(a,"text",c,d),Yvi(a,"paragraph",c,d)];a=new Vvi(b,a,null,null,null,null,null,null,null);c=a.D;for(b=0;b<c.length;b=b+1|0)if(!Zvi(c[b].C.D)&&Ec(Gxi,c[b].getType()))return!1;if(b1e((WN(),Pvi),a.C))return!1;for(c=0;c<Hxi.length;c=c+1|0)if(b=a.H[Hxi[c]],!Zvi(b?b:[]))return!1;return!0};function Jxi(a,b,c,d,e,f,h,k){B6.call(this,a,b,c,d,e,f,h,k);this.D=new Qv(void 0,k);this.Ia(this.D);this.ib=null;this.Za=ur(this,Kxi);this.ub=this.Ta=this.bb=!1;this.jb=this.ea=null}v(Jxi,B6);p=Jxi.prototype;p.tOa=function(){return Fxi};p.JWa=g("Za");p.initialize=function(){B6.prototype.initialize.call(this);var a=this.qa();this.ea=a.getElement(this.Za.gua);if(!this.ea)throw Error("No input element found");this.D.Wa(this.ea);this.Eb=new nw(this.ea);this.oa(this.Eb);this.ib=a.getElement(this.Za.YQa)};
p.Ja=function(){B6.prototype.Ja.call(this);this.getHandler().listen(this.Eb,"input",this.hZb)};p.hZb=function(){this.Ta=!0};p.Cva=function(){var a=B6.prototype.Cva.call(this);return a?a:this.D.isEnabled()?ae(this.D.getValue()):null};p.nza=function(a){a=B6.prototype.nza.call(this,void 0===a?0:a);return this.D.isEnabled()?pwi(a,this.D.getValue()):a};
p.nCa=function(){var a=mxi(this.F),b=a.getUrl();if(this.D.isEnabled()){var c=this.D.getValue();$d(ae(c))&&(c=a.C);this.D.setValue(c)}this.setVisible(!1);a=new hM(b,c);b=this.Fea();if(c){var d=new vPd;K(d,1,c.length);b.setSelectionRange(d)}c=uq(tq(new sq,1),b).build();O("docs-insert-link").kb(a,c)};p.R7=function(){var a=B6.prototype.R7.call(this);return this.D.isEnabled()?pwi(a,this.D.getValue()):a};
p.setContent=function(a,b,c){if(null!=b){this.O.Qa=0==b.length;b&&(this.Ta=!0,this.ub=b===a,this.jb=b);this.bb=!!b;var d=!0;c&&(d=Ixi(c));c=!!b.match((WN(),Qvi));!c&&d||this.D.Oa(!1);d?c?this.D.setValue("Cannot edit multi-paragraph selection."):(R(this.D.getElement(),!0),R(this.ib,!0),this.D.Oa(!0),this.D.setValue(b)):(R(this.D.getElement(),!1),R(this.ib,!1));this.Ea|=1}Dxi(this,a)};p.lWa=function(){try{this.ea&&!this.ea.disabled?this.ea.focus():Cxi(this)}catch(a){}};
p.CGa=function(a){B6.prototype.CGa.call(this,a);null!=a.anchorText&&Lxi(this,a.anchorText)};function Lxi(a,b){a.D.isEnabled()&&!a.Ta&&0<b.length&&a.D.setValue(b)}p.Fea=function(){var a=B6.prototype.Fea.call(this),b=M(a,$i,18);K(b,1,this.bb);K(b,9,this.ub);var c=this.D.isEnabled()&&this.D.getValue();if(c){var d=mxi(this.F).getUrl();K(b,3,c==d);ntc(d)&&K(b,10,!0)}K(b,11,this.jb!==c);return a};
p.reset=function(){B6.prototype.reset.call(this);this.Ta=!1;this.D.Oa(!0);this.ub=this.bb=!1;R(this.D.getElement(),!0);this.D.reset();this.jb=null};p.KCa=function(){var a=sk(Nj(this.ea));return B6.prototype.KCa.call(this)||a==this.ea};var Kxi={gua:"dlbti",YQa:"dlbtil"};function Mxi(a,b,c,d,e){S.call(this,e);this.D=a;this.F=b;this.C=c;this.H=d}v(Mxi,S);Mxi.prototype.Ca=function(){this.mb(this.qa().Ca("DIV",{"class":"waffle-insert-link-selection-overlay"}));this.getElement().style.top=this.D+"px";this.getElement().style.width=this.H-this.C+"px";this.getElement().style.left=this.C+"px";this.getElement().style.height=this.F-this.D+"px"};function Nxi(a){this.hb=eh(a,-1,0)}v(Nxi,hh);Nxi.prototype.toBuilder=function(){return new Oxi(this)};function Oxi(a){C.call(this,a)}v(Oxi,C);function Pxi(a,b){QG.call(this,78);this.Yc=a;this.C=b}v(Pxi,QG);Pxi.prototype.Nd=function(){var a=void 0===a?jh(Nxi):a;a=new Oxi(a);a=Ah(a,1,this.Yc);var b=Q9e(this.C);return Fh(a,2,b).build()};Pxi.prototype.ag=m(!1);function Qxi(a,b){this.C=a;this.D=b}function Exi(a){return Wea(sd(a.C.C.D,a.H,a),rd(sd(K4b(a.C.ma),a.F,a),function(b){return!!b}),[new z6("","","action","action",skb)])}Qxi.prototype.H=function(a){var b="#"+Zac(new Yac,a.gb()).build();return new z6(vf(a.Vd()),b,"infile","spreadsheet")};
Qxi.prototype.F=function(a){if(!a.isValid(this.C.C))return null;var b=a.getId(),c=N().pVb()(b);null===c&&(c=N().tja()(),this.D.C(new Pxi(c,new yU(null,b))));b="#"+$ac(new Yac,c).build();return new z6(vf(a.getName()),b,"infile","namedRange")};function Rxi(a){this.C=a};function Sxi(a){this.D=a}Sxi.prototype.C=function(a){var b="none",c=null;if(Jf&&2083<a.length)b="utl";else if(pF(a)){Zwi(a)?(rF(),c=TEa(Jn(a))?a:"mailto:"+Xa(a)):c=Txi(this,a);var d=rMb(a);Zwi(d)?d=Wl(1,d)?d.substring(d.indexOf(":")+1):d:d=Txi(this,d);a=Ywi(a)||Zwi(a)?!0:a.includes("/")?Ywi("http://"+a):!1;c=new kxi(c,d,a)}else b="invalid";return new lxi(b,c)};function Txi(a,b){var c=window.location.href;a.D&&(c=jd(A(),"docs-seu"));return tMb(b,c,c)&&(a=MAa(b))?"#"+a:b};function Uxi(a,b){this.D=a;this.F=b;this.H=new Sxi(a.D.H)}
Uxi.prototype.C=function(a){if(xWb.test(a)){if(qH(a,this.D.C,!1,!0)){var b=qH(a,this.D.C,!1,!0);b=N().oVb()(b.gid,b.rect.Pb(),b.rect.Lb(),b.rect.Vc(),b.rect.Xc());if(!b){b=N().tja()();var c=v6e(this.D.Va,a);this.F.C(new Pxi(b,c))}b="#"+$ac(new Yac,b).build();a=new lxi("none",new kxi(b,a,!0))}else a=new lxi("invalid",null,"Cell range doesn't look right. Typo?");return a}if(qF(a,window.location.href)){a:{if(b=MAa(a)){c=this.D.ub;var d=Oac(b);if(d&&!N().uVb()(d))if(b=Sac(c,b)){if(b=ND(b),c=NF(this.D.C,
b.gid)){b=sH(b.rect,c.Vd(),!0);break a}}else{b="#REF";break a}}b=null}if(b)return new lxi("none",new kxi(a,b,!0))}return this.H.C(a)};function Vxi(a){I(this,a,0,-1,Wxi,null)}x(Vxi,H);var Wxi=[2];Vxi.prototype.V=function(){var a=new D;var b=this.getContext();null!=b&&a.va(1,b,epe);b=J(this,2);0<b.length&&rQ(a,2,b);return Y(a)};Vxi.prototype.getContext=function(){return M(this,xP,1)};Vxi.prototype.setContext=function(a){return Pi(this,1,a)};Vxi.prototype.Wh=function(){return tQ(this,1)};function Xxi(a,b,c,d,e,f,h,k,l){h=void 0===h?"en":h;k=void 0===k?18E5:k;B.call(this);var n=this;this.F=a;this.J=d;this.eb=e;this.R=f;this.D=h;this.H=l||new Utd(b,c,4);this.oa(this.H);this.C=null;this.L=k;a=new ln(this.L);this.oa(a);b=new Pm(this);b.listen(a,"tick",this.O);this.oa(b);b=new Nm;this.oa(b);a.Tga();a.start();b.wb(this.J.C,function(q){3===q.getState()&&n.O()})}v(Xxi,B);
Xxi.prototype.O=function(){if(ao(this.F.F,2,0)){var a=this.J.getState();if(a&&(1!==a||this.eb.Nb().hasFocus())&&(a=Date.now(),!(this.C&&a-this.C<this.L))){this.C=a;var b=Xk(Sk(),"ssp");a=Rtd(this.F,this.D,this.R,function(){return $Ie()},jd(A(),"docs-egn"));a=(new Vxi).setContext(a);Vtd(this.H,a.pb()).addCallback(function(){return b.complete()})}}};function Yxi(a){I(this,a,0,-1,Zxi,$xi)}x(Yxi,H);var Zxi=[2],$xi=[[6,7]];Yxi.prototype.V=function(){var a=new D;var b=this.getContext();null!=b&&a.va(1,b,epe);b=zi(this,5);0<b.length&&a.Ba(5,b);b=J(this,6);null!=b&&a.Ba(6,b);b=J(this,7);null!=b&&a.Ba(7,b);b=xi(this,8,0);0!==b&&G(a,8,b);b=yi(this,9);0!==b&&a.Ua(9,b);b=J(this,2);0<b.length&&rQ(a,2,b);return Y(a)};Yxi.prototype.getContext=function(){return M(this,xP,1)};Yxi.prototype.setContext=function(a){return Pi(this,1,a)};
Yxi.prototype.Wh=function(){return tQ(this,1)};function ayi(a){I(this,a,0,-1,null,null)}x(ayi,H);ayi.prototype.V=function(){var a=new D;byi(this,a);return Y(a)};function byi(a,b){var c=zi(a,1);0<c.length&&b.Ba(1,c);c=a.getTitle();0<c.length&&b.Ba(2,c);c=zi(a,7);0<c.length&&b.Ba(7,c);c=zi(a,3);0<c.length&&b.Ba(3,c);c=a.getMimeType();0<c.length&&b.Ba(4,c);c=Ci(a,5);0!==c&&qQ(b,5,c);c=zi(a,6);0<c.length&&b.Ba(6,c);c=zi(a,8);0<c.length&&b.Ba(8,c)}ayi.prototype.getTitle=function(){return zi(this,2)};
ayi.prototype.setTitle=function(a){return Ki(this,2,a)};ayi.prototype.getMimeType=function(){return zi(this,4)};function cyi(a){I(this,a,0,-1,null,null)}x(cyi,H);cyi.prototype.V=function(){var a=new D;dyi(this,a);return Y(a)};function dyi(a,b){a=zi(a,1);0<a.length&&b.Ba(1,a)};function eyi(a){I(this,a,0,-1,fyi,null)}x(eyi,H);var fyi=[1];eyi.prototype.V=function(){var a=new D;gyi(this,a);return Y(a)};function gyi(a,b){var c=Oi(a,ayi,1);0<c.length&&ki(b,1,c,byi);c=xi(a,2,0);0!==c&&G(b,2,c);c=M(a,cyi,3);null!=c&&b.va(3,c,dyi)};function hyi(a){I(this,a,0,-1,null,null)}x(hyi,H);hyi.prototype.V=function(){var a=new D;iyi(this,a);return Y(a)};function iyi(a,b){var c=zi(a,1);0<c.length&&b.Ba(1,c);c=a.getTitle();0<c.length&&b.Ba(2,c);c=Ci(a,3);0!==c&&qQ(b,3,c);c=zi(a,4);0<c.length&&b.Ba(4,c);c=yi(a,7);0!==c&&b.Ua(7,c);c=yi(a,8);0!==c&&b.Ua(8,c)}hyi.prototype.getTitle=function(){return zi(this,2)};hyi.prototype.setTitle=function(a){return Ki(this,2,a)};function jyi(a){I(this,a,0,-1,kyi,null)}x(jyi,H);var kyi=[1];jyi.prototype.V=function(){var a=new D;lyi(this,a);return Y(a)};function lyi(a,b){var c=Oi(a,hyi,1);0<c.length&&ki(b,1,c,iyi);c=xi(a,2,0);0!==c&&G(b,2,c)};function myi(a){I(this,a,0,-1,nyi,null)}x(myi,H);var nyi=[1,2,5];myi.prototype.V=function(){var a=new D;oyi(this,a);return Y(a)};function oyi(a,b){var c=Oi(a,VR,1);0<c.length&&ki(b,1,c,UR);c=Oi(a,VR,2);0<c.length&&ki(b,2,c,UR);c=Oi(a,VR,5);0<c.length&&ki(b,5,c,UR);c=yi(a,3);0!==c&&b.Ka(3,c);c=M(a,VR,4);null!=c&&b.va(4,c,UR);c=M(a,VR,6);null!=c&&b.va(6,c,UR)};function pyi(a){I(this,a,0,-1,null,null)}x(pyi,H);pyi.prototype.V=function(){var a=new D;qyi(this,a);return Y(a)};function qyi(a,b){var c=a.getTitle();0<c.length&&b.Ba(1,c);c=a.getUrl();0<c.length&&b.Ba(2,c);c=zi(a,3);0<c.length&&b.Ba(3,c);c=zi(a,4);0<c.length&&b.Ba(4,c)}pyi.prototype.getTitle=function(){return zi(this,1)};pyi.prototype.setTitle=function(a){return Ki(this,1,a)};pyi.prototype.getUrl=function(){return zi(this,2)};function ryi(a){I(this,a,0,-1,syi,null)}x(ryi,H);var syi=[1];ryi.prototype.V=function(){var a=new D;tyi(this,a);return Y(a)};function tyi(a,b){var c=Oi(a,pyi,1);0<c.length&&ki(b,1,c,qyi);c=xi(a,2,0);0!==c&&G(b,2,c)};function uyi(a){I(this,a,0,-1,null,null)}x(uyi,H);uyi.prototype.V=function(){var a=new D;var b=M(this,eyi,5);null!=b&&a.va(5,b,gyi);b=M(this,ryi,6);null!=b&&a.va(6,b,tyi);b=M(this,jyi,9);null!=b&&a.va(9,b,lyi);b=M(this,myi,7);null!=b&&a.va(7,b,oyi);b=xi(this,8,0);0!==b&&G(a,8,b);return Y(a)};function vyi(a,b,c,d){this.C=b;this.D=d}v(vyi,rwi);vyi.prototype.getMimeType=g("D");function wyi(a,b){this.C=b}v(wyi,rwi);function xyi(a,b,c,d){B.call(this);this.H=a;this.J=b;this.F=c;this.D=d;this.C=new Map}v(xyi,B);
function yyi(a,b){var c=new Yxi;Gi(c,9,5);var d=Rtd(a.H,a.D,a.F,function(){return $Ie()},jd(A(),"docs-egn"));c.setContext(d);var e=new wNd,f=b.F;switch(f){case 2:Li(c,8,2);K(e,1,2);break;case 1:Li(c,8,1);K(e,1,1);break;default:return pl([])}if(kc(b.C))Ni(c,6,$xi[0],kc(b.C)),K(e,2,!1);else{var h=zyi(a),k=zyi(a);if(!h||!k)return pl([]);Ni(c,7,$xi[0],b.D);Ki(d,1,h);Ki(c,5,k);K(e,2,!0)}var l=Mvi(new Yi,Lvi(e)),n=Xk(Sk(),"els");c=Vtd(a.J,c.pb()).addCallback(function(q){q=new uyi(JSON.parse(q));return Ayi(a,
q,b,n,l)});if(a.C.has(f)&&a.C.get(f).equals(b))return pl([]);a.C.set(f,b);return SGa(c)}function Axi(a,b){return yyi(a,b)}
function Ayi(a,b,c,d,e){var f=c.F;d.complete(uq(tq(new sq,41),e).build());if(a.C.has(f))if(a.C.get(f).equals(c)||"placeholder"===c.D)a.C.delete(f);else return[];if(1===f){a=M(b,eyi,5);if(!a)return[];var h=si(a,3)?zi(M(a,cyi,3),1):null;return Oi(a,ayi,1).slice(0,Oi(a,ayi,1).length).filter(function(k){return null!==lwi(k.getMimeType(),zi(k,1),zi(k,8))}).map(function(k){var l=lwi(k.getMimeType(),zi(k,1),zi(k,8));if(y(A(),"docs-esckd"))k=new vyi(k.getTitle(),l,1,k.getMimeType(),h);else{var n=zi(k,7);
var q=k.getMimeType();q=-1!==q.indexOf("spreadsheet")?"spreadsheet":-1!==q.indexOf("presentation")?"presentation":"document";k=new z6(n,l,"drive",q,null,h,k.getMimeType())}return k})}return 2===f?(a=M(b,ryi,6))?Oi(a,pyi,1).slice(0,Oi(a,pyi,1).length).map(function(k){return y(A(),"docs-esckd")?new wyi(k.getTitle(),k.getUrl(),zi(k,3),1,zi(k,4)):new z6(vf(k.getTitle()),k.getUrl(),"web","link")}):[]:[]};function Byi(a,b,c,d){xyi.call(this,a.D,c,7,void 0===d?"en":d);this.O=a;this.L=b}v(Byi,xyi);function zyi(a){var b=xM(rJ(a.L));return b&&b.Mb()?b.getValue():(a=ZF(a.O.C))?CF(a,yG(a)).getDisplayValue():null};function Cyi(a,b,c,d,e,f,h,k,l,n,q){B.call(this);this.F=b;this.R=d;this.C=null;this.Pa=c;this.J=l;this.ma=n;this.Ha=h;this.L=this.O=null;this.Ea=f;this.Ma=k;this.H=this.D=null;this.xa=[];this.Aa=q;q.Fa("docs-insert-link").Oa(!0);skb.Oa(!0);this.ea=new Pm(this);this.oa(this.ea);this.Aa.Fa("docs-insert-link").subscribe("action",this.M3a,this);skb.subscribe("action",this.u7a,this);this.ea.listen(this.F.C,"za",this.Ggc);a=new Xxi(b.D,h,n,f,Lj(),7);this.oa(a)}v(Cyi,B);p=Cyi.prototype;
p.Lzc=function(a,b){this.C=a;if(a=rJ(this.J)){$M(a).Oa(!1);if(!this.D){var c=new Utd(this.Ha,this.ma,3);this.oa(c);c=new Byi(this.F,this.J,c);this.D=new Jxi(new Qxi(this.F,this.R),c,new Rxi(this.F.C),new Uxi(this.F,this.R),this.Ha,this.ma,ux(Mw.getInstance()));this.D.render(Oj("docs-editor-container"));this.oa(c);this.ea.listen(this.D,"hide",this.Vvb).listen(this.D.getElement(),"mouseup",this.Xvb)}this.D.setVisible(!0,!0);if(b){var d=rJ(this.J);(c=$M(d))&&c.oh()&&((d=xM(d))&&d.Mb()&&d.Ne(!0),c=c.oh(),
BG(this.C,c))}this.H=yG(this.C);c=a.H;d=xM(a);c&&c.C&&(c.C.JJ(),d.focus(),lic(d));Dyi(this,a,b);b=xM(a);b.Mb()?this.ma.C(36679):(kM(a),this.ma.C(36673));null!=this.O&&null!=this.L&&vK(b,this.O,this.L);Eyi(this);(b=a.H)&&b.C&&b.C.JJ();c=xM(a);a=CF(this.C,this.H);b=c&&c.Mb()?eic(c.getRange()):a.getDisplayValue();d=!c.Mb()&&a.YF();iB(b)||d?(b=APb(a)[0],this.D.setContent(b,a.getDisplayValue())):(a=bwi(c.getRange(),c.Ed()),this.D.setContent(a?a:"",b))}};
function Dyi(a,b,c){b=xM(b);if(c)a.O=c.C,a.L=c.D;else if(b.Mb()){b.focus();lic(b);var d=$hc(b.getElement(),b.getRange());c=Sgc(b.Ed(),d);d=Ugc(b.Ed(),d);vK(b,c,d);b.Ed()==sk(document)&&b.Mb()&&iic(b);a.O=Sgc(b.getElement(),b.getRange());a.L=Ugc(b.getElement(),b.getRange())}else b=eG(CF(a.C,a.H),a.C.Ib(),a.H.y,a.H.x),a.O=0,a.L=b.length}function Eyi(a){if(a.D.isVisible()){var b=yic(xM(rJ(a.J)),!0);awi(a.D,b.x,b.y);Fyi(a);mn(function(){rxi(a.D);a.Ea.Db(2)})}}
function Gyi(a){if(a.D.isVisible()){var b=rJ(a.J),c=tG(a.C,SC(a.H)),d=b.C;b=zJ(d,c.left,"c","page");c=zJ(d,c.top+1,"r","page");awi(a.D,b,c);c=new On(function(){rxi(a.D);a.Ea.Db(2)});a.oa(c);c.start()}}
p.M3a=function(a){var b=this,c=rJ(this.J);this.C=ZF(this.F.C);var d=a.getUrl();if(d&&c){y(A(),"docs-uatwt")&&Dyi(this,c);a=a.getText();var e=yG(this.C),f=CF(this.C,e),h=xM(c);h&&(null!=this.O&&null!=this.L?vK(h,this.O,this.L):lic(h));a||(a=h&&h.Mb()&&xic(h)?eic(h.getRange()):hG(f,this.C.Ib(),this.H.y,this.H.x));var k=new TKe(this.C,this.C.D,!1);this.R.C(k);(c=c.H)&&c.C.Mb()?(iB(h.getValue())&&h.setValue(""),f=fK(h),h=gK(h),c.C.mda(a,d,f,h)):(d=T7e(d,'"','""'),a=T7e(a,'"','""'),d==a&&"hyperlink"==
CPb(f)?Lod(this.F,this.C,e,d,null,this.R,function(){Hyi(b,e)}):(k=new KO(this.C,SC(e),'=HYPERLINK("'+d+'"'+this.Pa.D+'"'+a+'")'),this.R.C(k),Hyi(this,e)));this.Aa.Fa("docs-insert-link-dialog").Oa(!0)}};function Hyi(a,b){b=rH(b);a=PF(a.F.C,a.C.Ib()).Vd();OG("Link inserted at "+(b+(" in "+(a+"."))))}p.Vvb=function(a){if(a.target==this.D){(a=rJ(this.J))&&$M(a).Oa(!0);for(a=0;a<this.xa.length;a++)Xf(this.xa[a]);this.xa=[];this.Ea.Db(3)}};
p.Ggc=function(a){this.C&&a.jh==this.C.Ib()&&this.D&&(this.D.setVisible(!1),this.D.dispatchEvent("close"))};p.Na=function(){this.Aa.Fa("docs-insert-link").unsubscribe("action",this.M3a,this);skb.unsubscribe("action",this.u7a,this);Xf(this.D);B.prototype.Na.call(this)};p.Xvb=function(a){a.stopPropagation()};p.u7a=function(a){var b="",c=new Iyi(this.D);qH(a.getUrl(),this.F.C,!1,!0)&&(b=a.getUrl());xM(rJ(this.J)).Ne(!0);RU(this.Ma,this.D,c,b,!1,!1,!0,w(this.Wvb,this))};
p.Wvb=function(a){this.ea.Nc(a,"afterhide",w(this.Mzc,this))};
function Fyi(a){var b=xM(rJ(a.J)).getRange();var c=b?b.hs().getClientRects():[];b=new Map;c=ha(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,b.has(d.top)){var e=b.get(d.top);e.left=Math.min(e.left,d.left);e.right=Math.max(e.right,d.right);b.set(d.top,e)}else b.set(d.top,{top:d.top,bottom:d.bottom,left:d.left,right:d.right});b=Array.from(b.values());b=ha(b);for(c=b.next();!c.done;c=b.next())c=c.value,c=new Mxi(c.top,c.bottom,c.left,c.right),c.render(Oj("docs-editor-container")),a.xa.push(c)}
p.Mzc=function(){this.C.isDisposed()||WF(this.F.C)&&this.C==ZF(this.F.C)||this.F.C.Uz(this.C.Ib());!this.H||AG(this.C)&&Fj(this.H,yG(this.C))||BG(this.C,this.H);if(null!=this.O&&null!=this.L){var a=rJ(this.J);kM(a);vK(xM(a),this.O,this.L);Eyi(this);(a=a.H)&&a.C&&a.C.JJ()}else Gyi(this)};function Iyi(a){this.C=a}Iyi.prototype.setValue=function(a){Dxi(this.C,a);Lxi(this.C,a)};function Jyi(){Tn.apply(this,arguments)}v(Jyi,Tn);Jyi.prototype.C=function(){return Cyi};Fo("links",Jyi);
ØA—Eoúô   ˜¸¾™Ä      
!
GET
	docs-lfth1617671008658ÖÈ  "
accept-rangesbytes"
age349402"³
alt-svc§h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"")
cache-controlpublic, max-age=31536000"
content-encodinggzip"
content-length16621"
content-typetext/javascript"%
dateFri, 02 Apr 2021 00:00:05 GMT"(
expiresSat, 02 Apr 2022 00:00:05 GMT".
last-modifiedWed, 31 Mar 2021 19:54:36 GMT"
serversffe"
varyAccept-Encoding, Origin"!
x-content-type-optionsnosniff"
x-xss-protection00ñþ›Òš»ÇBYhttps://docs.google.com/static/spreadsheets2/client/js/2928354940-waffle_js_prod_links.jsHP&Zh3-29`jtext/javascriptrGET¬×¦Öš»ÇÄ³YßÑŽ%ÌêBù%lõ7ÿc²™“¤CM`ÔØA—Eoúô   üNú                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ÙÕù ¡c×   W‘è   \                                                                                                                                                                                                                                                                                                           